Repository toliner/desynced-ja, pull requests merged in 2023-08, with the labels that each got.

#2 Commander, we have discovered a structure that appears to be of の部分
  languages/ja.json
Labels: size/XS

#3 １１７８行から後。変更箇所、<MISSING TRANSLATION0>と最後に記載。
  languages/ja.json
Labels: size/XXL

#4 1178行から。（やり直し）
  languages/ja.json
Labels: size/XXL

#6 １０９２行に"You require a <hl>Power</> の追記
  languages/ja.json
Labels: size/XS

#7 １３１５行
  languages/ja.json
Labels: size/XS

#8 １１２５行
  languages/ja.json
Labels: size/XS

#9 JSON文法の修正
  languages/ja.json
Labels: size/XS

#10 Master
  languages/ja.json
Labels: size/M

#11 1408行から1421行まで
  languages/ja.json
Labels: size/S

#12 1422から1430行まで
  languages/ja.json
Labels: size/XS

#13 Explorable.lua 部分の修正
  languages/ja.json
Labels: size/L

#14 1130行、修正
  languages/ja.json
Labels: size/XS

#15 768行、修正
  languages/ja.json
Labels: size/XS

#16 食材→材料
  languages/ja.json
Labels: size/XS

#17 オプションメニュー周りの修正
  languages/ja.json
Labels: size/S

#18 ain/data/items.lua 部分の修正
  languages/ja.json
Labels: size/L

#20 JSON文法の修正
  languages/ja.json
Labels: size/XS

#21 Fix tag
  languages/ja.json
Labels: size/S

#22 freeplay_codex.lua 一部翻訳漏れ修正
  languages/ja.json
Labels: size/XS

#23 1111-1112行の合流。改行されてた
  languages/ja.json
Labels: size/XS

#24 1431から1435行まで
  languages/ja.json
Labels: size/XS

#25 <MISSING TRANSLATION>は終了
  languages/ja.json
Labels: size/L

#26 金属棒を金属インゴット（おためし）
  languages/ja.json
Labels: size/S

#27 チュートリアル部分のバグの修正
  languages/ja.json
Labels: size/XS

#28 オプションまわりと、ニューゲームの資源の豊かさ・最大量を追記
  languages/ja.json
Labels: size/S

#29 ストレージ・ブロック→貯蔵ブロック（テスト）
  languages/ja.json
Labels: size/XS

#30 スイッチ派閥→派閥の移動
  languages/ja.json
Labels: size/XS

#31 <br>になっているのを<bl>に修正
  languages/ja.json
Labels: size/S

#32 ポーズ・コンストラクション→建設一時停止
  languages/ja.json
Labels: size/XS

#33 Main/data/components.lua 一部対応
  languages/ja.json
Labels: size/L

#34 Main/ui/Faction.lua 修正
  languages/ja.json
Labels: size/L

#35 Minor Update 20230823 対応
  languages/ja.json
Labels: size/S

#37 「選手」→「プレーヤー」など
  languages/ja.json
Labels: size/M

#38 Main/ui/LoadSave.lua 修正対応
  languages/ja.json
Labels: size/M

#39 てにをは修正、def.jsonのバージョン修正
  def.json
  languages/ja.json
Labels: size/XS

#40 タグ周りと1105行の翻訳抜け
  languages/ja.json
Labels: size/XS

#41 オプションの修正と追記
  languages/ja.json
Labels: size/XS

#42 できる・できない を 出来る・出来ない に。
  languages/ja.json
Labels: size/L

#43 ストア→保管場所・GOTO→目的地 に変更
  languages/ja.json
Labels: size/M

#44 コーデックスの自動化２：パラメーターの英語の部分の修正
  languages/ja.json
Labels: size/M

#45 コーデックス 残りの英語部分の修正。（データキューブの説明が表示されない。）
  languages/ja.json
Labels: size/L

#47 出来る・出来ない を できる・できない に修正
  languages/ja.json
Labels: size/L

#46 Main/data/components.lua 対応
  languages/ja.json
Labels: size/L

#48 ニューゲーム のゲーム設定の変更
  languages/ja.json
Labels: size/L

#49 ９７６行
  languages/ja.json
Labels: size/XS

#51 Main/ui/Tech.lua 対応
  languages/ja.json
Labels: size/M

#52 １１３７行。\ の抜け
  languages/ja.json
Labels: size/XS

#53 1127行のミスの修正
  languages/ja.json
Labels: size/M

#54 Main/data/components.lua 修正
  languages/ja.json
Labels: size/L

#55 先祖返り修正
  languages/ja.json
Labels: size/L

#56 Optionsとキーバインド廻り
  languages/ja.json
Labels: size/M

#57 1410行 修正
  languages/ja.json
Labels: size/XS

#58 レジュメの構成→建築再開
  languages/ja.json
Labels: size/XS

#59 介さこと→通す事無く
  languages/ja.json
Labels: size/XS

#60 ビジュアル→視覚（おためし）
  languages/ja.json
Labels: size/S

#62 重複項目の削除
  languages/ja.json
Labels: size/XS

#63 1560行。ゲーム内の文章に。（原文はコメントに複製）
  languages/ja.json
Labels: size/XS

#65 チュートリアル後半の修正
  languages/ja.json
Labels: size/S

#61 ７８２行の修正
  languages/ja.json
Labels: size/XS

#66 2961行 ドローン保管→ドローン・ストレージ
  languages/ja.json
Labels: size/XS

#68 779 保管場所→転送
  languages/ja.json
Labels: size/XS

#67 Junn's branch
  languages/ja.json
Labels: size/L

#69 保管場所→転送 Storeの分
  languages/ja.json
Labels: size/S

#70 ミディアム ストレージ →中型ストレージ
  languages/ja.json
Labels: size/XS

#71 ミディアム・コンポーネント→中型コンポーネント
  languages/ja.json
Labels: size/XS

#72 マトリックス研究→マトリックス・テクノロジー
  languages/ja.json
Labels: size/XS

#74 建造物"Buildings nxn"の訳を建屋に変更
  languages/ja.json
Labels: size/S

#75 チュートリアル部分の更新等
  languages/ja.json
Labels: size/L

#76 1430行 高度な研究 の未翻訳分の修正
  languages/ja.json
Labels: size/XS

#77 シナリオメッセージの修正
  languages/ja.json
Labels: size/M

#78 アドバンスド・プロダクション→高度な生産
  languages/ja.json
Labels: size/XS

#79 UI周辺メッセージの修正
  languages/ja.json
Labels: size/S

#80 Main/data/instructions.lua 対応
  languages/ja.json
Labels: size/XL

#82 重複修正
  languages/ja.json
Labels: size/XS

#83 レジスタ名の統一
  languages/ja.json
Labels: size/L

#84 <TRANSLATION> の削除
  languages/ja.json
Labels: size/XL

#85 商品 → アイテム
  languages/ja.json
Labels: size/S

#86 用語の統一、微修正
  languages/ja.json
Labels: size/S

#87 Blight → ブライト 統一
  languages/ja.json
Labels: size/L

#88 用語の統一、微修正
  languages/ja.json
Labels: size/L

#89 用語の統一、微修正
  languages/ja.json
Labels: size/L

#90 GoTO→GoTo
  languages/ja.json
Labels: size/XS

#91 チュートリアル 一部修正
  languages/ja.json
Labels: size/L

#92 用語の統一、微修正
  languages/ja.json
Labels: size/S

#94 542行の品質に追記
  languages/ja.json
Labels: size/XS

#96 ミディアム・ソケット→中型ソケット
  languages/ja.json
Labels: size/S

#97 ストレージユニット→貯蔵ユニット
  languages/ja.json
Labels: size/XS

#99 重複修正
  languages/ja.json
Labels: size/XS

#100 Update ja.json
  languages/ja.json
Labels: size/XS

#101 「はじめに」Codexを修正
  languages/ja.json
Labels: size/S
