Repository toliner/desynced-ja, pull requests merged in 2023-09, with the labels that each got.

#102 ポーズ → 一時停止中
  languages/ja.json
Labels: size/XS

#103 血漿中濃度→ブライト濃縮
  languages/ja.json
Labels: size/XS

#104 Revert "血漿中濃度→ブライト濃縮"
  languages/ja.json
Labels: size/XS

#105 血漿中濃度→プラズマ濃縮
  languages/ja.json
Labels: size/XS

#107 Codexの改修
  languages/ja.json
Labels: size/M

#108 ブライトコンテナ 関係
  languages/ja.json
Labels: size/XS

#109 "building"の訳の揺れを統一
  languages/ja.json
Labels: size/L

#110 1497行 Build Menu →建設メニュー
  languages/ja.json
Labels: size/XS

#111 1497行 map overlay → 地図オーバーレイ
  languages/ja.json
Labels: size/XS

#112 1947行 ゲーム・チャット
  languages/ja.json
Labels: size/XS

#114 1500行 共有保管場所→共有ストレージ
  languages/ja.json
Labels: size/XS

#115 1159 シリカ
  languages/ja.json
Labels: size/XS

#116 1269 ブライト
  languages/ja.json
Labels: size/XS

#113 チュートリアル 一部修正
  languages/ja.json
Labels: size/M

#117 微修正　光→ブライト
  languages/ja.json
Labels: size/XS

#119 1473 ブライトガス
  languages/ja.json
Labels: size/XS

#120 1294行の追加 ブライト
  languages/ja.json
Labels: size/XS

#121 JSON不備修正
  languages/ja.json
Labels: size/XS

#122 人間・人類 （古代人と思われる文章）→ ヒューマン
  languages/ja.json
Labels: size/L

#123 チュートリアル 一部修正
  languages/ja.json
Labels: size/L

#124 ヒューマン 修正
  languages/ja.json
Labels: size/L

#126 Junn's branch
  def.json
  languages/ja.json
Labels: size/XL

#125 「パワー」を「電力」に書き換え
  languages/ja.json
Labels: size/M

#127 微調整、用語の統一
  languages/ja.json
Labels: size/S

#128 タイトルUI の修正
  languages/ja.json
Labels: size/L

#129 微調整、用語の統一
  languages/ja.json
Labels: size/L

#132 20230909対応: チュートリアル部分
  languages/ja.json
Labels: size/L

#131 オプションの修正
  languages/ja.json
Labels: size/M

#133 20230909 Codex
  languages/ja.json
Labels: size/M

#134 Junn's branch
  languages/ja.json
Labels: size/M

#135 Junn's branch
  languages/ja.json
Labels: size/M

#137 ログイン画面のアーリーアクセス表示の翻訳
  languages/ja.json
Labels: size/XS

#136 patch x2nd
  languages/ja.json
Labels: size/S

#139 20230909 誤字等修正
  languages/ja.json
Labels: size/S

#140 誤字等
  languages/ja.json
Labels: size/XS

#141 行動プログラム コマンド修正
  languages/ja.json
Labels: size/XS

#142 採掘機→採掘装置
  languages/ja.json
Labels: size/M

#143 微調整
  languages/ja.json
Labels: size/S

#145 Junn's branch
  languages/ja.json
Labels: size/L

#146 Junn's branch
  languages/ja.json
Labels: size/L

#144 Fix codex
  languages/ja.json
Labels: size/S
